import { writeFileSync } from "fs";
import * as path from "path";
import preprocessData from "./src/preprocessData";
import Context from "./src/Context";
import { renderNodes } from "./src/components";

export default function buildApi(apiFileName: string) {
  const rawSrc = require("../docsContent.json");
  const src = preprocessData(rawSrc);
  const res = renderNodes(src.children, new Context());

  const content = [
    "# Reform API docs",
    "",
    "> Autogenerated from source code",
    "",
    ...res,
  ].join("\n");

  const fileRoute = path.resolve(__dirname, apiFileName);
  writeFileSync(fileRoute, content);
  console.log(`BUILD API: generated ${fileRoute}`);
}
